"""srs review states and level definitions

Revision ID: 2516a51888b3
Revises: ea6bdeaa1c49
Create Date: 2026-09-16 13:16:23.543415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.level_seed_data import LEVEL_NAMES

revision: str = '2516a51888b3'
down_revision: Union[str, None] = 'ea6bdeaa1c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_definitions',
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('name_en', sa.String(length=40), nullable=False),
    sa.Column('name_fr', sa.String(length=40), nullable=False),
    sa.Column('icon_key', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('level')
    )
    op.create_table('review_states',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('lesson_node_id', sa.UUID(), nullable=True),
    sa.Column('repetitions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=4, scale=2), server_default='2.5', nullable=False),
    sa.Column('interval_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_rating', sa.SmallInteger(), nullable=True),
    sa.Column('current_level', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(card_id, lesson_node_id) = 1', name='ck_review_states_single_target'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_level'], ['level_definitions.level'], ),
    sa.ForeignKeyConstraint(['lesson_node_id'], ['hierarchy_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_states_user_card_uniq', 'review_states', ['user_id', 'card_id'], unique=True, postgresql_where=sa.text('card_id IS NOT NULL'))
    op.create_index('ix_review_states_user_due', 'review_states', ['user_id', 'due_at'], unique=False)
    op.create_index('ix_review_states_user_lesson_uniq', 'review_states', ['user_id', 'lesson_node_id'], unique=True, postgresql_where=sa.text('lesson_node_id IS NOT NULL'))
    op.create_table('review_logs',
    sa.Column('review_state_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('quality', sa.SmallInteger(), nullable=False),
    sa.Column('interval_before', sa.Integer(), nullable=False),
    sa.Column('interval_after', sa.Integer(), nullable=False),
    sa.Column('ease_before', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('ease_after', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['review_state_id'], ['review_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_review_state_id'), 'review_logs', ['review_state_id'], unique=False)
    op.create_index(op.f('ix_review_logs_user_id'), 'review_logs', ['user_id'], unique=False)
    # Note: autogenerate misreads the ltree 'path' column and proposes dropping
    # ix_hierarchy_nodes_path — that index is intentional, so this is omitted.
    # ### end Alembic commands ###

    level_definitions = sa.table(
        "level_definitions",
        sa.column("level", sa.SmallInteger),
        sa.column("name_en", sa.String),
        sa.column("name_fr", sa.String),
        sa.column("icon_key", sa.String),
    )
    op.bulk_insert(
        level_definitions,
        [
            {"level": level, "name_en": name_en, "name_fr": name_fr, "icon_key": icon_key}
            for level, name_en, name_fr, icon_key in LEVEL_NAMES
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_logs_user_id'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_review_state_id'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index('ix_review_states_user_lesson_uniq', table_name='review_states', postgresql_where=sa.text('lesson_node_id IS NOT NULL'))
    op.drop_index('ix_review_states_user_due', table_name='review_states')
    op.drop_index('ix_review_states_user_card_uniq', table_name='review_states', postgresql_where=sa.text('card_id IS NOT NULL'))
    op.drop_table('review_states')
    op.drop_table('level_definitions')
    # ### end Alembic commands ###
