"""categories and hierarchy

Revision ID: 6889a7f5d99c
Revises: 49d33f208d5f
Create Date: 2026-09-16 12:54:23.074349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.types import LtreeType

revision: str = '6889a7f5d99c'
down_revision: Union[str, None] = '49d33f208d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS ltree")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=80), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_owner_id'), 'categories', ['owner_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('hierarchy_nodes',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('path', LtreeType(), nullable=False),
    sa.Column('node_kind', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("node_kind IN ('group', 'lesson')", name='ck_hierarchy_nodes_node_kind'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['hierarchy_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hierarchy_nodes_category_id'), 'hierarchy_nodes', ['category_id'], unique=False)
    op.create_index(op.f('ix_hierarchy_nodes_owner_id'), 'hierarchy_nodes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_hierarchy_nodes_parent_id'), 'hierarchy_nodes', ['parent_id'], unique=False)
    op.execute(
        "CREATE INDEX ix_hierarchy_nodes_path ON hierarchy_nodes USING GIST (path)"
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['hierarchy_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    op.execute("DROP INDEX IF EXISTS ix_hierarchy_nodes_path")
    op.drop_index(op.f('ix_hierarchy_nodes_parent_id'), table_name='hierarchy_nodes')
    op.drop_index(op.f('ix_hierarchy_nodes_owner_id'), table_name='hierarchy_nodes')
    op.drop_index(op.f('ix_hierarchy_nodes_category_id'), table_name='hierarchy_nodes')
    op.drop_table('hierarchy_nodes')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_owner_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
