"""cards and images

Revision ID: ea6bdeaa1c49
Revises: 6889a7f5d99c
Create Date: 2026-09-16 13:05:24.359014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea6bdeaa1c49'
down_revision: Union[str, None] = '6889a7f5d99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('lesson_node_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('front_text', sa.Text(), nullable=False),
    sa.Column('back_text', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_node_id'], ['hierarchy_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_category_id'), 'cards', ['category_id'], unique=False)
    op.create_index(op.f('ix_cards_lesson_node_id'), 'cards', ['lesson_node_id'], unique=False)
    op.create_index(op.f('ix_cards_owner_id'), 'cards', ['owner_id'], unique=False)
    op.create_table('images',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('lesson_node_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('num_nonnulls(card_id, lesson_node_id) = 1', name='ck_images_single_owner_ref'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_node_id'], ['hierarchy_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_card_id'), 'images', ['card_id'], unique=False)
    op.create_index(op.f('ix_images_lesson_node_id'), 'images', ['lesson_node_id'], unique=False)
    op.create_index(op.f('ix_images_owner_id'), 'images', ['owner_id'], unique=False)
    # Note: autogenerate misreads the ltree 'path' column and proposes dropping
    # ix_hierarchy_nodes_path — that index is intentional (see the previous
    # migration), so that spurious drop/recreate is intentionally omitted here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_owner_id'), table_name='images')
    op.drop_index(op.f('ix_images_lesson_node_id'), table_name='images')
    op.drop_index(op.f('ix_images_card_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_cards_owner_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_lesson_node_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_category_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
